import { readdirSync, rmSync, statSync } from 'node:fs';
import { join } from 'node:path';
import { defineConfig } from 'wxt';

/**
 * The embedding runtime loads its WASM from `/ort/` (see utils/embedder.ts).
 * Vite also emits an unused copy under `assets/` while bundling Transformers.js;
 * drop it so the package doesn't ship the 23 MB binary twice.
 */
function removeRedundantWasm(dir: string): void {
  let entries: string[];
  try {
    entries = readdirSync(dir);
  } catch {
    return;
  }
  for (const entry of entries) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      removeRedundantWasm(full);
    } else if (/[/\\]assets[/\\]ort-wasm-.*\.wasm$/.test(full)) {
      rmSync(full);
      console.log(`ℹ Removed redundant bundled copy: ${entry}`);
    }
  }
}

export default defineConfig({
  hooks: {
    // WXT derives action.default_title from the popup's <title>, which would
    // override our value, so set the localized tooltip after the manifest is
    // generated. The __MSG_*__ tokens resolve from _locales/*/messages.json.
    'build:manifestGenerated'(_wxt, manifest) {
      manifest.action = { ...manifest.action, default_title: '__MSG_actionTitle__' };
    },
    'build:done'(wxt) {
      removeRedundantWasm(wxt.config.outDir);
    },
  },
  manifest: {
    // "Breadcrumb" is a brand name, so it stays the same in every language.
    // The description and toolbar tooltip are localized via _locales/*/messages.json
    // (generated by scripts/generate-locales.mjs). default_locale is the fallback.
    name: 'Breadcrumb',
    short_name: 'Breadcrumb',
    default_locale: 'en',
    description: '__MSG_extDescription__',
    permissions: ['storage', 'contextMenus', 'activeTab'],
    // On-device embeddings run through ONNX Runtime Web (WebAssembly), which
    // needs 'wasm-unsafe-eval' on extension pages. No remote code is executed.
    content_security_policy: {
      extension_pages:
        "script-src 'self' 'wasm-unsafe-eval'; object-src 'self'",
    },
  },
  zip: {
    name: 'breadcrumb',
    exclude: ['_metadata/**', '__MACOSX/**', '**/.DS_Store', '**/._*'],
    // Firefox AMO review ships a sources archive; keep the marketing site out of it.
    excludeSources: ['website/**'],
  },
});
